on
  push:
    tag:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: Release Build
    strategy:
      matrix:
        node-version: [16.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: tagcheck
      - run: |