run-name: workFlowTest
name: Action_1
on:
  push:
    branches:
      - test

jobs:
  Test1: # jobs그룹1
    name: Test1_name
    runs-on: ubuntu-latest
    steps:
      - run: echo 'jobs그룹1 - steps1'
      - name: test2
        run: echo 'jobs그룹1- steps2'
      - run: complete!!!!!
  Test2:
    runs-on: ubuntu-latest
    steps:
      run: Test2_steps_run
